name: Terraform Static Code Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - ".github/workflows/terraform-static-analysis.yml"

permissions:
  contents: read

jobs:
  terraform-static-analysis:
    permissions:
      pull-requests: write
    name: Terraform Static Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        fetch-depth: 0
    - name: Run Analysis
      uses: ministryofjustice/github-actions/terraform-static-analysis@7dcfd542251caa78f93eb118cb44e578fb7fdc6e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        scan_type: single
        tfsec_exclude: aws-cloudwatch-log-group-customer-key, aws-iam-no-policy-wildcards, aws-vpc-no-public-egress-sgr, aws-iam-block-kms-policy-wildcard, aws-vpc-add-description-to-security-group
        checkov_exclude: CKV_GIT_1

  terraform-static-analysis-full-scan:
    permissions:
      pull-requests: write
    name: Terraform Static Analysis - scan all directories
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        fetch-depth: 0
    - name: Run Analysis
      uses: ministryofjustice/github-actions/terraform-static-analysis@7dcfd542251caa78f93eb118cb44e578fb7fdc6e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        scan_type: full
        tfsec_exclude: aws-cloudwatch-log-group-customer-key, aws-iam-no-policy-wildcards, aws-vpc-no-public-egress-sgr, aws-iam-block-kms-policy-wildcard, aws-vpc-add-description-to-security-group
        checkov_exclude: CKV_GIT_1
