name: Terraform Static Code Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - ".github/workflows/terraform-static-analysis.yml"
jobs:
  terraform-static-analysis-full-scan:
    permissions:
      pull-requests: write
    name: Terraform Static Analysis - scan all directories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Run Analysis
        uses: ministryofjustice/github-actions/terraform-static-analysis@5abe121df74f6cf546fba4a3fc2ab1f960ed43ab # v11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scan_type: full
          tfsec_exclude: AWS089, AWS099, AWS009, AWS097, AWS018
          checkov_exclude: CKV_GIT_1
